### ISSUE TITLE
ERROR:tensorflow:Model diverged with loss = NaN

### ISSUE THREAD

**Issue by michaelnguyen11** [open-edge-platform/geti#107]
Hi supporters,

I intent to train a face detection model using training_toolbox_tensorflow and WIDER face dataset which are converted to COCO format. The config.py is as same as vlp/config.py, and I changed annotation_path to WIDER face path.
But when run train.py, i am facing with a problem "ERROR:tensorflow:Model diverged with loss = NaN"
I searched in the stackoverflow, tensorflow and following their instructions but still failed.

Did you meet the same problem before ?
Do you know how to overcome this issue ?

Thank you in advance !

Regards,
Michael

-  I have searched the [issues](https://github.com/opencv/training_toolbox_tensorflow/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
    If you're describing a bug, tell us what should happen.
    If you're suggesting a change/improvement, tell us how it should work.

## Current Behavior
    If describing a bug, tell us what happens instead of the expected behavior.
    If suggesting a change/improvement, explain the current behavior.

## Steps to Reproduce (for bugs)

1. Convert Wider face to COCO format (I use tools in this repo :https://github.com/the-house-of-black-and-white/morghulis)
2. add full image path for above COCO format
3. Change `annotation_path` in `vlp/config.py` to Wider face COCO format
4. start training "python3 tools/train.py vlp/config.py"

## Context
    How has this issue affected you? What are you trying to accomplish?
    Providing context helps us come up with a solution that is most useful in the real world.

## Your Environment

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Conda
- TensorFlow version (use command below): 1.12.0
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```
- Python version: 3.6.8
- CUDA/cuDNN version: 7.6.0 build cuda9.0_0
- GPU model and memory: nvidia geforce gtx 1050 4G, NVIDIA-SMI 390.116

    Include as many relevant details about the environment with which you experienced the bug.

**Comment by AlexanderDokuchaev** [comment]
Hi @michaelnguyen11 

Unfortunaly, we did not try to train on WIDER faces.
Look at [PyTorch object detection](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/object_detection), it newer model that based on [mmdetection](https://github.com/open-mmlab/mmdetection) toolkit and have better precision.

**Comment by michaelnguyen11** [comment]
Hi @AlexanderDokuchaev ,

Thank you so much for your response.

I've trained the pytorch [face detection](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/object_detection/face_detection.md) above, but when load face_detector.onnx model to OpenCV with API : net = cv::dnn::readNetFromONNX("face_detector.onnx"), I got errors :
`
/media/opencv/modules/dnn/src/layers/prior_box_layer.cpp:241: error: (-215:Assertion failed) !params.has("step") in function 'PriorBoxLayerImpl'
`
On the other hand, when i try to convert onnx format to tensorflow format with repo : https://github.com/onnx/onnx-tensorflow, I got another problems:

```
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for PriorBoxClustered with domain_version of 9
==> Context: Bad node spec: input: "477" input: "input.1" output: "486" op_type: "PriorBoxClustered" attribute { name: "clip" i: 0 type: INT } attribute { name: "flip" i: 0 type: INT } attribute { name: "height" floats: 15 floats: 39.6 floats: 25.5 floats: 63.2 floats: 227.5 floats: 162.9 floats: 124.5 floats: 105.1 floats: 72.6 type: FLOATS } attribute { name: "img_h" i: 0 type: INT } attribute { name: "img_size" i: 0 type: INT } attribute { name: "img_w" i: 0 type: INT } attribute { name: "offset" f: 0.5 type: FLOAT } attribute { name: "step" f: 16 type: FLOAT } attribute { name: "step_h" f: 0 type: FLOAT } attribute { name: "step_w" f: 0 type: FLOAT } attribute { name: "variance" floats: 0.1 floats: 0.1 floats: 0.2 floats: 0.2 type: FLOATS } attribute { name: "width" floats: 9.4 floats: 25.1 floats: 14.7 floats: 34.7 floats: 143 floats: 77.4 floats: 128.8 floats: 51.1 floats: 75.6 type: FLOATS }
```

Do you think this is a bug of "tools/ssd_export_helpers.py" or did I miss something while training as [face detection instruction](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/object_detection/face_detection.md)

Thank you in advance !

Regards,
Michael

**Comment by AlexanderDokuchaev** [comment]
@michaelnguyen11  It is expected, onnx does not support `PriorBoxClustered`.
We used onnx as intermediate stage to convert to OpenVINO format..

You can build [OpenCV with IE backend](https://github.com/opencv/opencv/wiki/Intel's-Deep-Learning-Inference-Engine-backend) or look on [dldt sample](https://github.com/opencv/dldt/tree/2019/inference-engine/samples/object_detection_sample_ssd) to run model in OpenVino format (.xml and .bin)

**Comment by michaelnguyen11** [comment]
Thank a lot for the information and your support.
