### ISSUE TITLE
Bitvehicle dataset

### ISSUE THREAD

**Issue by davidrij** [open-edge-platform/geti#186]
The bitvehicle dataset used in the tensorflow ssd detection tutorial is not available under the link in the readme, is there another way to obtain it?

**Comment by AlexanderDokuchaev** [comment]
@davidrij 
Yeap, we know about it. 
But unfortunately, we didnt find any mirror. And we have no legal approve to publish BITVehicle dataset by ourselves, but we are trying get it.

**Comment by junshixiansheng** [comment]
链接: https://pan.baidu.com/s/1VcZ5ZueySTgLhyNrAB5wGg 提取码: bfx6

**Comment by richardgohth** [comment]
> 
> 
> @davidrij
> Yeap, we know about it.
> But unfortunately, we didnt find any mirror. And we have no legal approve to publish BITVehicle dataset by ourselves, but we are trying get it.

Is it possbile to populate with a couple of sample images, do that we can try out the process first , then populate with our own dataset?

**Comment by AlexanderDokuchaev** [comment]
@richardgohth 
> Is it possbile to populate with a couple of sample images, do that we can try out the process first , then populate with our own dataset?

https://github.com/opencv/openvino_training_extensions/tree/develop/data/vlp_test

> I can provide some images, annotated in .txt format ( below ). Will you be able to provide conversion scripts to annotation in json format?
It will good. Yes, i help with converting to json.

**Comment by LorenzoLamberti94** [comment]
Are those new images available by any chance?
It would be much appreciated!

**Comment by richardgohth** [comment]
HI
We found that SG plates are not suitable for LPRNet.
1. They are multi row
2. They have spaces and characters are kerned
Also LPRNet does not provide a measure of confidence.

We have stopped using LPRnet in favour of our traditional segmentation type LPR.
