### ISSUE TITLE
lpr tensorflow

### ISSUE THREAD

**Issue by hlacikd** [open-edge-platform/geti#198]
**Describe the bug**

there is a problem in a way a vocabulary is build to decode beams .
When I am at my computer, inference works and license plates are recognized correctly
when i deploy same code (in both cases same docker!) to different machine, all license plates have final vocabs shifted +1. Example : correct 6AB1234, on different machine 7BC2345!

**Steps to Reproduce**

1. download openvino training extensions
2. do your own trainging
3. run on one PC , works okay
4. run on other PC (mb different locales??) all vocabs are shifted

**Environment:**
 - OS: 
 - Framework version: 
 - Python version:
 - OpenVINO version:
 - CUDA/cuDNN version: 10.1
 - GPU model and memory: GTX1080, 6G

**Comment by AlexanderDokuchaev** [comment]
@hlacik 
Vocabulary to decode output of network is created in [_create_standard_vocabs](https://github.com/opencv/openvino_training_extensions/blob/1c4db62e56069067563f8c22c3e030164e03282f/tensorflow_toolkit/lpr/lpr/trainer.py#L245) function, that read train and val annotation files to get all used characters. 
To use lpr model in your inference code you should use static list of characters.

**Comment by hlacik** [comment]
thank you Alexander, I already figured it out (had "-" character in annotation file) and for deployment I used dockerfile which created empty train val files (touch val && touch train) which caused to have different vocabulary during training and deployment. I do appreciate tho your answer!!
