### ISSUE TITLE
ImportError: cannot import name 'get_dist_info'

### ISSUE THREAD

**Issue by muhammad-maaz-confiz** [open-edge-platform/geti#245]
While converting pre-trained pytorch person_vehicle_bike detector model to ONNX format using command 
```
python tools/onnx_export.py configs/person_vehicle_bike_sd512_mb2_clustered.py checkpoint/person_vehicle_bike_sd512_mb2_clustered_epoch_21.pth onnx/person_vehicle_bike_sd512_mb2_clustered.onnx
```

I am getting the error 

```
File "/home/maaz/PycharmProjects/openvino_training_extensions/external/mmdetection/mmdet/datasets/loader/sampler.py", line 7, in <module>
    from mmcv.runner.utils import get_dist_info
ImportError: cannot import name 'get_dist_info
``` 

I build the mmdetection module as follows,
```
git clone https://github.com/sovrasov/mmdetection.git
git checkout b0ef8ab
python setup.py develop
./compile.sh
```

My environment is as follows,
* python -> 3.6.10
* torch -> 1.1.0
* torchvision -> 0.2.2 (I also tried torchvision==0.3.0)
* Cuda Toolkit -> 10.0 (I aslo tried 10.2)
* mmcv -> 0.4.0

Please let me know what I am doing wrong, also please guide me with the solution. Thanks

**Comment by AlexanderDokuchaev** [comment]
Hi @muhammad-maaz-confiz 
Downgrade mmcv to 0.2.10 version that have 
`pip3 install mmcv==0.2.10`
It should works. Requirement.txt will be updated soon.

**Comment by muhammad-maaz-confiz** [comment]
Thanks mmcv==0.2.10 works for me.
