### ISSUE TITLE
LPR training train.py : "ModuleNotFoundError: No module named 'lpr'"

### ISSUE THREAD

**Issue by tunicashashi** [open-edge-platform/geti#27]
## Expected Behavior
    Training should start for the new data set configured.
## Current Behavior
    Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from lpr.toolbox.utils import dataset_size
ModuleNotFoundError: No module named 'lpr'
;
## Steps to Reproduce (for bugs)
Training LPRnet Model based on the Readme file
1.To start training go to training_toolbox/lpr directory and type in command line:

python3 train.py chinese_lp/config.py

## Context
    It didn't allowed me to run the train.py

# Solution suggestion
Change the location of the train.py or change in the from import lpr.toolbox

## Your Environment

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from anaconda:
- TensorFlow version 1.10
```

```
- Python version:
3.6.6

    Include as many relevant details about the environment with which you experienced the bug.

**Comment by alexey-trushkov** [comment]
Did you setup virtual environment how's written in `README`?

**Comment by tunicashashi** [comment]
@alexey-trushkov Yes, I setup and used virtual environment in the anaconda environment where I had installed Intel optimized tensorflow. But when I run "nosetests" I get issue like:

"anaconda3/envs/my_env/lib/python3.6/site-packages/jpeg4py-0.1.4-py3.6.egg/jpeg4py/_py.py", line 215, in __del__
AttributeError: 'JPEG' object has no attribute 'decompressor'
Exception ignored in: <bound method JPEG.__del__ of <jpeg4py._py.JPEG object at 0x7f726a5f91d0>>
"
SO I ignore and tried to run train.py with exporting the PYTHONPATH as

export PYTHONPATH=$PYTHONPATH:$home/training_toolbox_tensorflow/training_toolbox/lpr/

**Comment by alexey-trushkov** [comment]
Actually you should not export PYTHONPATH manually, since it's done during steps 4 and 5 in readme

> 3. Create virtual environment
> <a name="create_venv"></a>
> 
>   ```
>   bash tools/init_venv.sh
>   ```
> 
> 4. Start to work
> 
>   ```
>   cd /<path_to_working_dir>/training_toolbox_tensorflow
>   . venv/bin/activate
>   ```

But if you do you it should export `training_toolbox` folder not `lpr`: 

`export PYTHONPATH=$PYTHONPATH:$home/training_toolbox_tensorflow/training_toolbox`
