### ISSUE TITLE
Why not the eval.py  print the final result instead of the "||||||......."

### ISSUE THREAD

**Issue by junxnone** [open-edge-platform/geti#31]
It's very weird when the eval.py is done. it still print the "|||||......". 
https://github.com/opencv/training_toolbox_tensorflow/blob/develop/training_toolbox/ssd_detector/eval.py#L171

**Comment by alexey-trushkov** [comment]
@junxnone eval.py prints  this`|||||......` while awaiting for the new checkpoint. What's your suggestion?
