### ISSUE TITLE
While running the eval.py file it is printing "|||||....."

### ISSUE THREAD

**Issue by BhargaviChintanippu** [open-edge-platform/geti#32]
Hi,
 
OS : UBUNTU - 16.04 version
After running eval.py file it is printing "||||...." continuously and the process is not stopping. Could you please suggest why eval.py file is  not printing a valid result? 

TIA ,
Bhargavi.

**Comment by tunicashashi** [comment]
same as issue #31

**Comment by alexey-trushkov** [comment]
@BhargaviChintanippu could you please provide more info how to reproduce this issue. Do you have at least one checkpoint in the model folder?

**Comment by BhargaviChintanippu** [comment]
@alexey-trushkov I have trained 25000 steps and so there are 25000 checkpoints in model folder.

**Comment by alexey-trushkov** [comment]
@BhargaviChintanippu What config do you use for training?

**Comment by BhargaviChintanippu** [comment]
I downloaded training_toolbox_tensorflow-at-add-lpr.zip from github and used config file from that add-lpr folder only....But for validation that config is throwing some error..so used other config which you posted in github...

**Comment by alexey-trushkov** [comment]
You've used branch at/add-lpr, so first of all please try current develop branch with lpr code. And file bug using proposed template in order i could reproduce it.
