### ISSUE TITLE
eval.py  is printing "|||||||....."

### ISSUE THREAD

**Issue by BhargaviChintanippu** [open-edge-platform/geti#34]
After setting up, downloaded training_toolbox_tensorflow-develop from github and trained the synthetic chinese plates for 50000 steps, and while running the eval.py file for validation it is checking GT Label and then after showing Test acc and Time per step,it is printing "|||||....." and the validation process is not ending.

## Expected Behavior
Expected a valid result

## Current Behavior
Validation process is not finishing, it is printing "|||||...." while running the eval.py file

## Your Environment

-  Ubuntu 16.04):
- TensorFlow installed from binary:
- TensorFlow version 1.12.0

```

- Python version:
- python3 - 3.5.2
- CUDA/cuDNN version: 7.5

**Comment by ashish1405** [comment]
Hello Bhargavi, you closed this issue, were you able to solve it? what you did, can you please describe.
