### ISSUE TITLE
How can I get the confidence scores of LPRNet?

### ISSUE THREAD

**Issue by jayer95** [open-edge-platform/geti#352]
Hi, I have already referred to this issues, and I have read lprnet paper.
https://github.com/openvinotoolkit/training_extensions/issues/238

I need to get a confidence scores like openalpr.
https://github.com/openalpr/openalpr

I tried to use the function of CTCGreedyDecoder in tensorflow 1.15.0 to get confidence or probability, but still no results.

How does LPRNet support in tensorflow 2.3? 
Can I use tf.raw_ops.CTCGreedyDecoder to obtain log_probability or confidence in tensorflow 2.3? I tried it, but there are many bugs.
https://www.tensorflow.org/api_docs/python/tf/raw_ops/CTCGreedyDecoder?hl=zh-cn

Please help, I need to get similar confidence scores in any outputs messages or shapes on LPRNet, how can I get the "confidence" scores of LPRNet?

I have the same problem with https://github.com/openvinotoolkit/training_extensions/issues/238.

Thanks very much!
-Newbie

**Comment by jayer95** [comment]
@Ilya-Krylov  
Thanks a lot, 
May I ask you, does it support angle changes in 3 dimensions?
For example, plus or minus 30 degrees, and the rotation of the xyz axis.
I also want to ask you if it supports STNet?

**Comment by Ilya-Krylov** [comment]
It might be said that it's primary oriented on horizontally aligned text because of model architecture, but it might learn how to work with curved and rotated text if it is trained on such data. Currently it is not. You may try to do it by yourself.

It does not support STNet.
