### ISSUE TITLE
Can i train the number plate in two lines?

### ISSUE THREAD

**Issue by nyanmn** [open-edge-platform/geti#39]
If I like to train number plate with two lines, it is possible to train using the same approach. Or where should i modify?

**Comment by lanybass** [comment]
Split into 2 lines by yourself, then 1 by 1. I guess....

**Comment by alexey-trushkov** [comment]
@nyanmn currently no, either you have to modifying current code or improve your license plate detector which will distinguish where region with 1'st line and 2'nd.
