### ISSUE TITLE
LocNet of Spatial Transformer Layer in LPRNet

### ISSUE THREAD

**Issue by b04505009** [open-edge-platform/geti#406]
I want to train a LPRNet model with Spatial Transformer Layer, but the model is not good at recognizing rotated plates. I would like to know where the code for LocNet mentioned in LPRNet is, as I only saw a function transformer() which do identity transform with little noise, and did not see any network related to this. Thank you for your help!

**Comment by Ilya-Krylov** [comment]
There is no LocNet (which is described in the paper) implemented in OTE.
