### ISSUE TITLE
where is spatial_transformer

### ISSUE THREAD

**Issue by lanybass** [open-edge-platform/geti#41]
https://github.com/opencv/training_toolbox_tensorflow/blob/734bfc649cbfced7ecb0bde73a1645a5cb9ad418/training_toolbox/lpr/trainer.py#L7

**Comment by alexey-trushkov** [comment]
@lanybass It's imported from object detection api, see

https://github.com/opencv/training_toolbox_tensorflow/blob/42b9b47f889cf1fbb26dc8e2534ef42be85d59cf/training_toolbox/utils/helpers.py#L17

and used while initializing lpr module: 

https://github.com/opencv/training_toolbox_tensorflow/blob/42b9b47f889cf1fbb26dc8e2534ef42be85d59cf/training_toolbox/lpr/__init__.py#L3

**Comment by lanybass** [comment]
thank you~

**Comment by AlexZll** [comment]
But I can't still find the py file called spatial_transformer. @alexey-trushkov You only told him where the file should be placed.
