### ISSUE TITLE
lpr pretrained model url is out of date

### ISSUE THREAD

**Issue by lanybass** [open-edge-platform/geti#42]
in readme.md:
"Trained model: LPRNet 94x24. " is not exist.
the correct url is : https://download.01.org/openvinotoolkit/training_toolbox_tensorflow/models/lpr/chinese_lp/license-plate-recognition-barrier-0007.tar.gz

**Comment by lanybass** [comment]
would you add project of trainning the vehicle_attributes model in future?

**Comment by kennethchn** [comment]
> in readme.md:
> "Trained model: LPRNet 94x24. " is not exist.
> the correct url is : https://download.01.org/openvinotoolkit/training_toolbox_tensorflow/models/lpr/chinese_lp/license-plate-recognition-barrier-0007.tar.gz
我测试发现，车牌中地名识别效果非常差，不知道是模型本身问题，还是我程序有问题？

**Comment by lanybass** [comment]
> > in readme.md:
> > "Trained model: LPRNet 94x24. " is not exist.
> > the correct url is : https://download.01.org/openvinotoolkit/training_toolbox_tensorflow/models/lpr/chinese_lp/license-plate-recognition-barrier-0007.tar.gz
> > 我测试发现，车牌中地名识别效果非常差，不知道是模型本身问题，还是我程序有问题？

对于数据集中的车牌还好啊，eval的正确率有98%+。自己找的图片来识别，大部分错的确实是汉字.一是因为汉字确实比字符复杂，二是，单个车牌里，数字和字母有6个样本，而汉字只有一个样本，所以相对来所，汉字得到的训练较少。
还有就是图片的矫正比较重要，他训练的图都是矫正过的，对没矫正过的歪斜车牌识别率很低

**Comment by kennethchn** [comment]
发自我的 陈康

在 2019年3月5日，下午11:20，YunLan <notifications@github.com<mailto:notifications@github.com>> 写道：


in readme.md:
"Trained model: LPRNet 94x24. " is not exist.
the correct url is : https://download.01.org/openvinotoolkit/training_toolbox_tensorflow/models/lpr/chinese_lp/license-plate-recognition-barrier-0007.tar.gz
我测试发现，车牌中地名识别效果非常差，不知道是模型本身问题，还是我程序有问题？

对于数据集中的车牌还好啊，eval的正确率有98%+。自己找的图片来识别，大部分错的确实是汉字.一是因为汉字确实比字符复杂，二是，单个车牌里，数字和字母有6个样本，而汉字只有一个样本，所以相对来所，汉字得到的训练较少。
还有就是图片的矫正比较重要，他训练的图都是矫正过的，对没矫正过的歪斜车牌识别率很低
