### ISSUE TITLE
tensorboard  is incompatible.

### ISSUE THREAD

**Issue by zhou7jing** [open-edge-platform/geti#43]
Do the steps to setup, the tensorboard is incompatible. 

## Current Behavior
  When I wanna create the virtual environment by provided step(bash tools/init_venv), the tensorboard is incompatible. But I thought I use the right tensorboard version.

## Steps to Reproduce (for bugs)

1.run "~/training_toolbox_tensorflow$ bash tools/init_venv.sh"
2.tensorflow-gpu 1.10.0 has requirement tensorboard<1.11.0,>=1.10.0, but you'll have tensorboard 1.12.2 which is incompatible.
3.When I check the pip list:
tensorboard                   1.10.0                
tensorflow                    1.10.0                
tensorflow-gpu                1.10.0                
tensorflow-tensorboard        1.5.1 

## Your Environment

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04
- TensorFlow installed from (source or binary):1.10.0
- TensorFlow version (use command below):1.10.0
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```
- Python version:2.7/3.5

- GPU model and memory:

**Comment by lanybass** [comment]
you can install tf from conda by yourself without run init_venv.sh. I have tried 1.10 1.12, that's ok.

**Comment by lanybass** [comment]
你为什么用python 3.5? 貌似3.6兼容性更好

**Comment by zhou7jing** [comment]
whatever 3.5 or 3.6, I found the inconsistent PYTHONPATH led to this problem. After uniting the PYTHONPATH, the environment is built successfully.
Thank you very much for your response!


When I run the nosetests, the import-error appear:ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory.
Is it running based on CUDA? Why this Error appear(i didn't use CUDA，I use a intel nuc without nv's GPU)

**Comment by lanybass** [comment]
哪个文件import了libcublas?
我搜了下他源码里没有用到啊。
你是不是在这个目录运行的nosetests哦

**Comment by lanybass** [comment]
gpu环境他写的是可选，我在windows上自己conda装的GPU环境跑train.py没问题，没执行他的init和test

**Comment by zhou7jing** [comment]
我调用tensorflow的时候出现的这个importError应该是没有找到我的tensorflow，我把它弄好了，现在又出现了 File "/home/abc/.local/lib/python3.5/site-packages/pycocotools/coco.py", line 308, in loadRes
    if type(resFile) == str or type(resFile) == unicode:
NameError: name 'unicode' is not defined
明明2to3这个库我装了呀。。为啥还有这个问题

**Comment by lanybass** [comment]
https://github.com/cocodataset/cocoapi/issues/49

**Comment by zhou7jing** [comment]
好了，i deleted "or type(resFile) == unicode"  . It works!

**Comment by zhou7jing** [comment]
@lanybass Thanks a lot!

**Comment by zhou7jing** [comment]
@lanybass 最后做Lpr推理的时候，一次只能进去一张车牌图片？
我推理路径设置两个以上的时候，只出来第一张推理的结果，如何显示第二张图片以及第三第四张图片？
推理出第一张照片的时候我按键盘上下建就会出现：“TypeError: Fetch argument array([b'/home/abc/Downloads/Synthetic_Chinese_License_Plates/crops/066006.png'],
      dtype=object) has invalid type <class 'numpy.ndarray'>, must be a string or Tensor. (Can not convert a ndarray into a Tensor or Operation.)
”

**Comment by zhou7jing** [comment]
Can this tool do the retrain job?

**Comment by lanybass** [comment]
> @lanybass 最后做Lpr推理的时候，一次只能进去一张车牌图片？
> 我推理路径设置两个以上的时候，只出来第一张推理的结果，如何显示第二张图片以及第三第四张图片？
> 推理出第一张照片的时候我按键盘上下建就会出现：“TypeError: Fetch argument array([b'/home/abc/Downloads/Synthetic_Chinese_License_Plates/crops/066006.png'],
> dtype=object) has invalid type <class 'numpy.ndarray'>, must be a string or Tensor. (Can not convert a ndarray into a Tensor or Operation.)
> ”

这是个bug,变量被覆盖了，改一下变量名：

> vals, **_one_batch_filenames_** = sess.run([d_predictions, filenames])
    pred = decode_beams(vals, config.r_vocab)  
    for i, filename in enumerate(**_one_batch_filenames_**):

两个filenames改成其他的，我改成了one_batch_filenames
----------------
retrain?这就是从头训练啊。你说的retrain是指Fine-tune吗？
