### ISSUE TITLE
python infer.py vlp/config.py --video --input=./1.mp4 --show

### ISSUE THREAD

**Issue by lfydegithub** [open-edge-platform/geti#44]

**Comment by lfydegithub** [comment]
> InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,3,3,16] rhs shape= [3,3,3,32]
> 
> the model is "0126_ssd_mobilenet_v2_1.zip"

**Comment by lanybass** [comment]
why do you closed?
How to resolve?
