### ISSUE TITLE
Instructions in training_extensions/web/CPU_README.md do not work

### ISSUE THREAD

**Issue by pigubaoza** [open-edge-platform/geti#454]
**Describe the bug**
Running the instructions, found in CPU_README.md, up till the step
`IDLP_HOST=localhost docker-compose -f docker-compose.cpu.yml up --build -d`

I get the following error:
```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '../ote/requirements.txt'
Requirement already satisfied: opencv-python in /usr/local/lib/python3.7/dist-packages (4.5.1.48)
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.7/dist-packages (from opencv-python) (1.20.1)
ERROR: Service 'idlp_train_worker' failed to build: The command '/bin/sh -c cat requirements.txt | xargs -n 1 -L 1 pip install' returned a non-zero code: 123
```

**Environment:**
 - OS: Linux Ubuntu 16.04
 - Framework version: NA
 - Python version: NA
 - OpenVINO version: NA
 - CUDA/cuDNN version: NA
 - GPU model and memory: NA

**Comment by Ilya-Krylov** [comment]
@pigubaoza  , we put on hold development of Web UI and removed it from the repo, since it is not currently supported.
