### ISSUE TITLE
ImportError: libcublas.so.9.0

### ISSUE THREAD

**Issue by dremsol** [open-edge-platform/geti#49]
When trying to run nosetests in venv as described following error occurs;
`ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory`

when trying to run `import tensorflow as tf` as a separate python command the same error returns. Seems this has something to do with CPU/GPU version of tensorflow?!

**Comment by zhou7jing** [comment]
in the virtual environment, reinstall tensorflow
I met this problem last week.

**Comment by willemremie** [comment]
Thanks for your reply. Apparently it only works by uninstalling the tensorflow-gpu package. Nosetests is running but is failing;
`FAIL: test_train (tests.ssd_detector.train_net_test.TrainNetCheckRegression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/remsol/Downloads/openvino_training_extensions/tensorflow_toolkit/tests/ssd_detector/train_net_test.py", line 47, in test_train
    self.check_detections(path.join(CONFIG.ROOT_DIR, 'data/test/default_setup/gold_predictions.json'))
  File "/home/remsol/Downloads/openvino_training_extensions/tensorflow_toolkit/tests/ssd_detector/train_net_test.py", line 63, in check_detections
    self.assertAlmostEqual(val, val_gold, msg='Detections mismatch')
AssertionError: 499.4 != 424.5 within 7 places : Detections mismatch
`

**Comment by AlexanderDokuchaev** [comment]
Hi @willemremie 
It's ok. Currently our integration tests works only in CPU mode.
