### ISSUE TITLE
pretrained model is not match for ssd

### ISSUE THREAD

**Issue by lanybass** [open-edge-platform/geti#51]
I've downloaded the model weight([MobileNet v2 0.35 256x256.](https://download.01.org/openvinotoolkit/training_toolbox_tensorflow/models/ssd_detector/vlp/0123_ssd_mobilenet_v2_0.35.1_barrier_256x256.zip)) from the readme file of **ssd_detector**, but it dosen't work for infering or training.
- [X] I have searched the [issues](https://github.com/opencv/training_toolbox_tensorflow/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
    If you're describing a bug, tell us what should happen.
    If you're suggesting a change/improvement, tell us how it should work.
I ran train.py or infer.py, turn out an error:
```
    saver.restore(sess, checkpoint_filename_with_path)
  File "d:\ProgramData\Anaconda3\envs\tfg12\lib\site-packages\tensorflow\python\training\saver.py", line 1562, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key global_step not found in checkpoint
         [[node save/RestoreV2 (defined at infer_ssd.py:105)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
         [[{{node save/RestoreV2/_79}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_84_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save/RestoreV2', defined at:
...........
```
key: **Key global_step not found in checkpoint**  
I've no idea how to rescue.  
## Current Behavior
    If describing a bug, tell us what happens instead of the expected behavior.
    If suggesting a change/improvement, explain the current behavior.

## Steps to Reproduce (for bugs)

1.download the weight,unzip to vlp
2.change the filename in checkpoint file in model dir
3.run python infer.py --video --input E:\a.mp4  vlp\config.py
4.bingo~ the error come out

## Context
    How has this issue affected you? What are you trying to accomplish?
    Providing context helps us come up with a solution that is most useful in the real world.

## Your Environment

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):b'unknown' 1.12.0
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```
- Python version:3.6.8
- CUDA/cuDNN version: 10.0.130 / 7.3.1
- GPU model and memory: 2080TI 11G

    Include as many relevant details about the environment with which you experienced the bug.

**Comment by alexey-trushkov** [comment]
@lanybass try to set 'initial_weights_path'  to checkpoint from archive  [MobileNet v2 0.35 256x256 ](https://download.01.org/openvinotoolkit/training_toolbox_tensorflow/models/ssd_detector/vlp/0123_ssd_mobilenet_v2_0.35.1_barrier_256x256.zip), and start training at least for one iteration (when weights will be loaded in and stored in new checkpoint) then use newly created checkpoint, it should work.

**Comment by lanybass** [comment]
it works.thanks~~
