### ISSUE TITLE
infer using .pb model

### ISSUE THREAD

**Issue by tienduchoang** [open-edge-platform/geti#53]
hello @snosov1 . Thank for your code. Can you help me to infer license plate using .pb model?

**Comment by Daniil-Osokin** [comment]
For quick test you can use [infer.py](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/infer.py) script. But probably you want to [convert](https://software.intel.com/en-us/articles/OpenVINO-Using-TensorFlow) the model and use it inside the [demo](https://docs.openvinotoolkit.org/R5/_samples_security_barrier_camera_demo_README.html).

**Comment by snosov1** [comment]
Hey, @tienduchoang ! Hopefully, it answers your question. Thx, @Daniil-Osokin !
