### ISSUE TITLE
Can I use transfer Learning for LPRNet using Chinese LP trained checkpoint/.pb file 

### ISSUE THREAD

**Issue by tunicashashi** [open-edge-platform/geti#54]
Do the LPRnet model support Transfer learning, if so then how can I do if I have checksum for Chinese Licenceplate

**Comment by grib0ed0v** [comment]
@tunicashashi it heavily depends on what you call `support Transfer learning` - very often, it just means that you start with pre-trained model and then fine-tune it with new data. So, in this scenario, you are OK to start from our weights.

**Comment by UforU** [comment]
@grib0ed0v Yes, I mean to start with pre-trained model and use your weights. Can you tell me about which file should I modify for it and where should I look ? Should I look in train.py

**Comment by grib0ed0v** [comment]
@UforU actually this code is already written, you just need to put snapshot with correct name in correct folder. See [code in train.py](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/train.py#L79-L82)
