### ISSUE TITLE
not able to export model for person-detection-0203

### ISSUE THREAD

**Issue by Pked01** [open-edge-platform/geti#563]
Hello
I trained person-detection-0203 
but while using export step i am not able to get alt_ssd_export model(for openvino) 
i used following command 
`python export.py --load-weights output/latest.pth --save-model-to inference_graph/ --openvino --onnx`

**Comment by Ilya-Krylov** [comment]
`alt_ssd_export` is for [SSD](https://arxiv.org/abs/1512.02325), but person-detection-0203 is [ATSS](https://arxiv.org/abs/1912.02424)
