### ISSUE TITLE
link is not working!

### ISSUE THREAD

**Issue by yustiks** [open-edge-platform/geti#57]
link that is described in project is not working: https://download.01.org/openvinotoolkit/open_model_zoo/training_toolbox_pytorch/models/hpe/checkpoint_iter_370000.pth
"The requested URL was not found on this server."

- [x] I have searched the [issues](https://github.com/opencv/training_toolbox_tensorflow/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
    If you're describing a bug, tell us what should happen.
    If you're suggesting a change/improvement, tell us how it should work.

## Current Behavior
    If describing a bug, tell us what happens instead of the expected behavior.
    If suggesting a change/improvement, explain the current behavior.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
    How has this issue affected you? What are you trying to accomplish?
    Providing context helps us come up with a solution that is most useful in the real world.

## Your Environment

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```
- Python version:
- CUDA/cuDNN version:
- GPU model and memory:

    Include as many relevant details about the environment with which you experienced the bug.

**Comment by Daniil-Osokin** [comment]
Hi Yustina, thanks for the report! We are working on this issue, in the meantime model is available by the old link: https://download.01.org/openvinotoolkit/open_model_zoo/training_toolbox_pytorch/models/hpe/checkpoint_iter_370000.pth.tar. @snosov1, can you please fix this.

**Comment by Daniil-Osokin** [comment]
@AlexanderDokuchaev @snosov1 It should have extension `.pth`. Can you please rename it?

**Comment by AlexanderDokuchaev** [comment]
@Daniil-Osokin, Done. New path: https://download.01.org/openvinotoolkit/open_model_zoo/training_toolbox_pytorch/models/hpe/checkpoint_iter_370000.pth

**Comment by Daniil-Osokin** [comment]
Wow, thanks!
