### ISSUE TITLE
not able to get "output_node_names" from trained lpr model

### ISSUE THREAD

**Issue by mahinlma** [open-edge-platform/geti#68]
Trained lpr model with NVDIA GPU. Using checkpoint & meta data generated .pb.
When I tried summarize graph with .pb received.
Not able to get "Output_node_names".

To freeze .pb, I need output_node_names.
Please provide solution to fix this

**Comment by AlexanderDokuchaev** [comment]
Hi @mahinlman,
Try to use the script [lpr/export.py](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/export.py), that contain code for freezing lpr graph.

**Comment by mahinlman** [comment]
Thank you.  @AlexanderDokuchaev

**Comment by abdou31** [comment]
@AlexanderDokuchaev Please can you re-upload the script, because the link is broken
Thanks.

**Comment by AlexanderDokuchaev** [comment]
@abdou31 script was moved to `tools` directory.
https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/tools/export.py

**Comment by abdou31** [comment]
Thanks.
I hope that this script worked for me
