### ISSUE TITLE
How to export FP16 model by export.py 

### ISSUE THREAD

**Issue by feolcn** [open-edge-platform/geti#76]
- [checked ] I have searched the [issues](https://github.com/opencv/training_toolbox_tensorflow/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
    It is work on GPU or Movidius with FP16 Model

## Current Behavior
     The result text  display alot of zero，e.g“Y000000000000000000000000000000000000000000000000000000000000000000000000000000000000000” .

## Steps to Reproduce (for bugs)

1. export the FP16 model
2. change the source of export.py  line 55 and 86 from FP32 to FP16 
3. get the bin and xml file
4. put the file to the correct place.

## Context
    I can not get the right result .

## Your Environment

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu 16.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.10.0
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```
- Python version:3.5
- CUDA/cuDNN version:9.0 7
- GPU model and memory:

    Include as many relevant details about the environment with which you experienced the bug.

**Comment by AlexanderDokuchaev** [comment]
Hi, @feolcn 

Can not reproduce your problem on GPU.

- Which version of OpenVINO do you have?
- Did you use trained model from download.01.org or train own model?
- Did you check output of frozen graph and FP32 model on CPU?

**Comment by feolcn** [comment]
@AlexanderDokuchaev 

- the version of OpenVINO is 2019.1

- I have used the modle from download.01.org ,adn it worked,I trained my modle follow the readme txt.

- I have verifyed the model(FP32) on CPU ,it is worked .but when I export the model to FP16 use on GPU or the MYRIAD,it is not work.

**Comment by feolcn** [comment]
@AlexanderDokuchaev 
the attachment is my FP16 modle , i thine maybe there is something wrong with the xml file .
I just use this file https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/export.py  
and change the source of export.py line 55 and 86 from FP32 to FP16 to export my FP16 modle for Myriad,
now the wrong msg change to  Segmentation fault .
[ie_model.zip](https://github.com/opencv/openvino_training_extensions/files/3216947/ie_model.zip)

**Comment by AlexanderDokuchaev** [comment]
@feolcn 
Thank you to provide your model.
In finally, i have reproduced the issue but only when run model on Movidius NCS. On GPU fp16 models work correctly. 
We need some time to fix this issue. I will keep you informed about any update.

**Comment by feolcn** [comment]
@AlexanderDokuchaev 
thanks a lot

**Comment by feolcn** [comment]
@AlexanderDokuchaev 
How about this bug,  it can not work with the new export.py on FP16 。

**Comment by AlexanderDokuchaev** [comment]
@feolcn it looks like problem in plugin for NCS, still waiting for response from developer team.

**Comment by AlexanderDokuchaev** [comment]
@feolcn Good news. Bug was fixed. In next release OpenVINO 2019R3 this model will work on NCS.

**Comment by feolcn** [comment]
@AlexanderDokuchaev  thanks a lot, Could you tell me when the 2019R3 will release?
or could you give me a patch or something else which could make it works on 2018R2?

**Comment by AlexanderDokuchaev** [comment]
@feolcn 
*2019R3*should be available in the second half of september.
About provide to you fixed version, i should get a consultation.

**Comment by feolcn** [comment]
@AlexanderDokuchaev Thank you for your reply

**Comment by AlexanderDokuchaev** [comment]
@feolcn Unfortunately, i can not provide you nightly build or something else to make it works with current release :disappointed:

**Comment by feolcn** [comment]
@AlexanderDokuchaev thank you, anyway. I will wait for the 2019R3 to check it.

**Comment by AlexanderDokuchaev** [comment]
@feolcn  [2019R3](https://software.intel.com/openvino-toolkit) now available to download.

**Comment by feolcn** [comment]
@AlexanderDokuchaev  I have downloaded the 2019R3, thank you
