### ISSUE TITLE
output format pose estimation

### ISSUE THREAD

**Issue by yustiks** [open-edge-platform/geti#77]
I needed to implement json output for the pose estimation for every image. I can't understand all the parameters of the network. 
So we have pose_entries and all_keypoints, what do they mean?
pose_entries is an array of 20 elements, 18 elements are responsible for each points in a pose (-1 if there are no points, the number means the line number of all_keypoints array. What does mean 19th element? Confidence? 
 all_keypoints has a vector of 4 elements. What does mean the 3d and 4th? As I understood, 3d is confidence, and 4th is just a # of element. Is it correct?

**Comment by Daniil-Osokin** [comment]
Hi,
* `all_keypoints` is a list of keypoints for all poses found in image. Each element is a keypoint with its confidence and global id, represented as tuple with 4 elements: 0, 1 - keypoints coordinates, 2 - keypoint confidence (value from heatmap) and the last one is global keypoint id in this list.
* `pose_entries` is a list of poses. Each pose is a list of 20 elements: [0,17] - global keypoints ids, 18 is pose confidence (sum of keypoints confidences and confidences of connections between keypoints), the last one is number of found keypoints for pose.

We've recently added class [Pose](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/human_pose_estimation/demo.py#L112), may be it can help here.

**Comment by snosov1** [comment]
@Daniil-Osokin do you think it makes sense to make these details part of the documentation?

**Comment by Daniil-Osokin** [comment]
If this post gather 10+ :+1:, then we will think about it =).

**Comment by snosov1** [comment]
Hey, @Daniil-Osokin ! Seems like the request is popular in the community!

**Comment by Daniil-Osokin** [comment]
OMG, I should write 100...

**Comment by Daniil-Osokin** [comment]
:fire: #83
