### ISSUE TITLE
how can I infer an image directly?

### ISSUE THREAD

**Issue by ShaneYS** [open-edge-platform/geti#79]
in official code, if we want to infer images, we should generate "infer.file_list_path (test_infer)" firstly, and then the code will read the image path in test_infer.

if I just want to infer one image, and read the image directly,  how to modify the code?

**Comment by AlexanderDokuchaev** [comment]
Hi @ShaneYS 

You can see example of code in [infer.py](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/tools/infer.py) (for frozen graph) or [infer_ie.py](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/tools/infer_ie.py) (for IR). 
But firstly you should [export model](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/lpr#export-to-openvino) by [tools/export.py](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/lpr#export-to-openvino). 

You can read instruction in [README.md](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/README.md),  that was updated today https://github.com/opencv/openvino_training_extensions/pull/74.
