### ISSUE TITLE
Poor performance of lprNet inference for unaligned plate images (plate images with margin)

### ISSUE THREAD

**Issue by farshadopencv** [open-edge-platform/geti#86]
I successfully trained a model of LPRNet plate recognition by using [this tutorial](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/lpr), on my own plate dataset. The images in my dataset are tight aligned crop and have **no margin**. Inference result of my trained model on plate images without any margin is very very good. But, when i pass an plate **_ with margin_** to the model, I receive a strange result, including 20 characters, whereas my plate has only 8 characters. How can I resolve this issue? Do I need to train my model with plate images with margin? In this case, I encounter another problem. The size of margins in plate images, changes from one image to another, meaning that, the margins don't have a fixed size. How can i get a good result for plate images with margins? any recommendations would be appreciated.

**Comment by AlexanderDokuchaev** [comment]
Hi @farshadopencv 
Yes, in this case you should train model using images with margin.
In ideal, you should use the some detection algorithm when crop original images to create training dataset and when used final model. 
But if it's not possible, you can try add augmentation function to generate border. In alternative, you can add preprocessing function to cut plates without margin.
