### ISSUE TITLE
Unexpected Error When running instance_segmentation 

### ISSUE THREAD

**Issue by Yang507** [open-edge-platform/geti#87]
Traceback (most recent call last):
   File "tools/train.py", line 215, in <module>
      main(args)
   File "tools/train.py", line 177, in main
     train_tool.model = locate(args.model)(train_dataset.classes_num)
   File "/usr/lib/python3.5/pydoc.py", line 1575, in locate
     nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
   File "/usr/lib/python3.5/pydoc.py", line 350, in safeimport
     raise ErrorDuringImport(path, sys.exc_info())
  pydoc.ErrorDuringImport: problem in segmentoly.rcnn.model_zoo.resnet_fpn_mask_rcnn -   ImportError: No module named 'segmentoly.extensions._EXTRA'

**Comment by AlexanderDokuchaev** [comment]
Hi @Yang507 
Do you have installed CUDA in your environment?

**Comment by Yang507** [comment]
@AlexanderDokuchaev 
yes, I do.
 
> nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by DmitriySidnev** [comment]
@Yang507 @AlexanderDokuchaev Hi!
It looks like that the module `segmentoly` was not installed. @Yang507, did you make steps from the installation guide?

**Comment by hiankun** [comment]
Hi, I faced the similar problem when trying to run `demo.py`.

I noticed that the `pytorch_toolkit/instance_segmentation` has no `init_venv.sh` included. I've copied one from another folder and created a virtualenv to run the samples accordingly. But when I tried to run `pip3 install -e .` the process failed.

My question is: Can we setup `pytorch_toolkit/instance_segmentation` in virtualenv? Or what part keeps us from doing so?

**Comment by AlexanderDokuchaev** [comment]
@hiankun Yes, you can use virtualenv. 

Do you have same error `pydoc.ErrorDuringImport: problem in segmentoly.rcnn.model_zoo.resnet_fpn_mask_rcnn - ImportError: No module named 'segmentoly.extensions._EXTRA'` ?

**Comment by hiankun** [comment]
Hi, @AlexanderDokuchaev 

My problem here is that I can't install `segmentoly` within virtualenv.

I've setup the virtualenv which installed packages given by `requirements.txt` (but I commented out the `numpy` line, which seemed messing the version of numpy which might be installed by my OpenVINO 2019 R3).

I can import modules such as `cv2` and `torch` in the virtualenv, but when I did `pip3 install -e .` it returned the following error message:
```
btaining file:///media/thk/storage/sandbox_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation                                                                
Installing collected packages: segmentoly                                           
  Found existing installation: segmentoly 0.0.0                                     
    Not uninstalling segmentoly at /media/thk/storage/sandbox_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation, outside environment /media/thk/storage/sand
box_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation/venv    
    Can't uninstall 'segmentoly'. No files were found to uninstall.             
  Running setup.py develop for segmentoly
    ERROR: Command errored out with exit status 1: 
```
and followed by long error output.

BTW, I have successfully run `pip3 install -e .` in my another system (Ubuntu 16.04) without virtualenv. It installed `segmentoly` smoothly. (although I got some problems when running the demo code with my own trained models, but that's should be another issue and I will post that in a new thread...)

**Comment by michaelnguyen11** [comment]
I solved the issue in conda environment by uninstalling torch==0.4.1 and then install pytorch==1.3.1
If you can't import torch like this:
```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
```
let's uninstall numpy and install numpy again with command :
`pip install numpy -I`

The segmentoly will be installed smoothly.

**Comment by dbAIStudio** [comment]
@michaelnguyen11 Hello, after you use torch1.3, do you install other python packages to modify it, can you train normally?

**Comment by Ilya-Krylov** [comment]
Segmentoly does not exist anymore, if someone is interested in instance segmentation models please have a look at https://github.com/openvinotoolkit/training_extensions#models
