### ISSUE TITLE
Unexpected Error When running human_pose training

### ISSUE THREAD

**Issue by Yang507** [open-edge-platform/geti#88]
yh@yh-DJ-H310M-E:~/tutorials/openvino_training_extensions/pytorch_toolkit/human_pose_estimation$ python3 train.py --train-images-folder ../../data/coco/train2017/ --prepared-train-labels prepared_train_annotation.pkl --val-labels val_subset.json --val-images-folder ../../data/coco/val2017/ --checkpoint-path models/mobilenet_sgd_68.848.pth.tar --from-mobilenet

[WARNING] Not found pre-trained parameters for model.0.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.1.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.1.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.2.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.2.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.3.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.3.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.4.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.4.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.5.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.5.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.6.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.6.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.7.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.7.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.8.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.8.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.9.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.9.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.10.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.10.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.11.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.11.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for cpm.align.0.weight
[WARNING] Not found pre-trained parameters for cpm.align.0.bias
[WARNING] Not found pre-trained parameters for cpm.trunk.0.0.weight
[WARNING] Not found pre-trained parameters for cpm.trunk.0.2.weight
[WARNING] Not found pre-trained parameters for cpm.trunk.1.0.weight
[WARNING] Not found pre-trained parameters for cpm.trunk.1.2.weight
[WARNING] Not found pre-trained parameters for cpm.trunk.2.0.weight
[WARNING] Not found pre-trained parameters for cpm.trunk.2.2.weight
[WARNING] Not found pre-trained parameters for cpm.conv.0.weight
[WARNING] Not found pre-trained parameters for cpm.conv.0.bias
[WARNING] Not found pre-trained parameters for initial_stage.trunk.0.0.weight
[WARNING] Not found pre-trained parameters for initial_stage.trunk.0.0.bias
[WARNING] Not found pre-trained parameters for initial_stage.trunk.1.0.weight
[WARNING] Not found pre-trained parameters for initial_stage.trunk.1.0.bias
[WARNING] Not found pre-trained parameters for initial_stage.trunk.2.0.weight
[WARNING] Not found pre-trained parameters for initial_stage.trunk.2.0.bias
[WARNING] Not found pre-trained parameters for initial_stage.heatmaps.0.0.weight
[WARNING] Not found pre-trained parameters for initial_stage.heatmaps.0.0.bias
[WARNING] Not found pre-trained parameters for initial_stage.heatmaps.1.0.weight
[WARNING] Not found pre-trained parameters for initial_stage.heatmaps.1.0.bias
[WARNING] Not found pre-trained parameters for initial_stage.pafs.0.0.weight
[WARNING] Not found pre-trained parameters for initial_stage.pafs.0.0.bias
[WARNING] Not found pre-trained parameters for initial_stage.pafs.1.0.weight
[WARNING] Not found pre-trained parameters for initial_stage.pafs.1.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.initial.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.initial.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.0.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.0.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.0.1.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.0.1.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.0.1.running_mean
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.0.1.running_var
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.0.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.1.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.1.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.1.1.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.1.1.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.1.1.running_mean
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.1.1.running_var
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.0.trunk.1.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.initial.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.initial.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.0.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.0.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.0.1.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.0.1.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.0.1.running_mean
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.0.1.running_var
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.0.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.1.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.1.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.1.1.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.1.1.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.1.1.running_mean
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.1.1.running_var
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.1.trunk.1.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.initial.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.initial.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.0.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.0.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.0.1.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.0.1.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.0.1.running_mean
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.0.1.running_var
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.0.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.1.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.1.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.1.1.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.1.1.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.1.1.running_mean
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.1.1.running_var
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.2.trunk.1.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.initial.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.initial.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.0.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.0.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.0.1.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.0.1.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.0.1.running_mean
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.0.1.running_var
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.0.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.1.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.1.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.1.1.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.1.1.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.1.1.running_mean
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.1.1.running_var
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.3.trunk.1.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.initial.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.initial.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.0.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.0.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.0.1.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.0.1.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.0.1.running_mean
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.0.1.running_var
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.0.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.1.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.1.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.1.1.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.1.1.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.1.1.running_mean
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.1.1.running_var
[WARNING] Not found pre-trained parameters for refinement_stages.0.trunk.4.trunk.1.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for refinement_stages.0.heatmaps.0.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.heatmaps.0.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.heatmaps.1.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.heatmaps.1.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.pafs.0.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.pafs.0.0.bias
[WARNING] Not found pre-trained parameters for refinement_stages.0.pafs.1.0.weight
[WARNING] Not found pre-trained parameters for refinement_stages.0.pafs.1.0.bias
Traceback (most recent call last):
  File "train.py", line 170, in <module>
    args.checkpoint_after, args.val_after)
  File "train.py", line 80, in train
    for batch_data in train_loader:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 469, in __init__
    w.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by Daniil-Osokin** [comment]
Hi, 
The warnings are ok, they tell that provided checkpoint has no pre-trained weights for some layers (this is true, it has weights only for feature extractor layers). And the error is `Cannot allocate memory`, try to set less number of workers: `--num-workers 2` or smaller batch size.

**Comment by Yang507** [comment]
@Daniil-Osokin Thanks, i'd solved it
