### ISSUE TITLE
Could you share how tow to train/val dataset LIP in detail?

### ISSUE THREAD

**Issue by YOKE** [open-edge-platform/geti#95]
@AlexanderDokuchaev

**Comment by AlexanderDokuchaev** [comment]
Hi @YOKE 

1. Download files from http://47.100.21.47:9999/overview.php use GoogleDrive or BaiduDrive:
   * `TrainVal_pose_annotations.zip`
   * `TrainVal_images.zip`
   * `Testing_images.zip`
2. Extract all archives to <LIP_HOME>. 

```
unzip Testing_images.zip -d <LIP_HOME>
unzip <LIP_HOME>/Testing_images.zip -d <LIP_HOME>

unzip TrainVal_images.zip -d <LIP_HOME>
unzip <LIP_HOME>/TrainVal_images.zip -d <LIP_HOME>

unzip TrainVal_pose_annotations.zip  -d <LIP_HOME>
```

You should have:
```
<LIP_HOME>
├── Testing_images
│   ├── test_id.txt
│   └── testing_images [10000 entries exceeds filelimit, not opening dir]
├── TrainVal_images
│   ├── train_id.txt
│   ├── train_images [30462 entries exceeds filelimit, not opening dir]
│   ├── val_id.txt
│   └── val_images [10000 entries exceeds filelimit, not opening dir]
└── TrainVal_pose_annotations
    ├── lip_train_set.csv
    ├── lip_val_set.csv
    ├── README.md
    └── vis_annotation.py
```

**Comment by YOKE** [comment]
> Hi @YOKE
> 
> 1. Download files from http://47.100.21.47:9999/overview.php use GoogleDrive or BaiduDrive:
>    
>    * `TrainVal_pose_annotations.zip`
>    * `TrainVal_images.zip`
>    * `Testing_images.zip`
> 2. Extract all archives to <LIP_HOME>.
> 
> ```
> unzip Testing_images.zip -d <LIP_HOME>
> unzip <LIP_HOME>/Testing_images.zip -d <LIP_HOME>
> 
> unzip TrainVal_images.zip -d <LIP_HOME>
> unzip <LIP_HOME>/TrainVal_images.zip -d <LIP_HOME>
> 
> unzip TrainVal_pose_annotations.zip  -d <LIP_HOME>
> ```
> 
> You should have:
> 
> ```
> <LIP_HOME>
> ├── Testing_images
> │   ├── test_id.txt
> │   └── testing_images [10000 entries exceeds filelimit, not opening dir]
> ├── TrainVal_images
> │   ├── train_id.txt
> │   ├── train_images [30462 entries exceeds filelimit, not opening dir]
> │   ├── val_id.txt
> │   └── val_images [10000 entries exceeds filelimit, not opening dir]
> └── TrainVal_pose_annotations
>     ├── lip_train_set.csv
>     ├── lip_val_set.csv
>     ├── README.md
>     └── vis_annotation.py
> ```

Thanks for your guide! I want to work at Single-Person Human Pose Estimation on LIP, would I just change the datasets.coco in train.py to datasets.lip?  Do I need to change anything else?

**Comment by AlexanderDokuchaev** [comment]
@YOKE you should follow instruction from https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/human_pose_estimation/README_single.md
