### ISSUE TITLE
Unexpected Error When running python3.6 train_single.py --dataset-folder <LIP_HOME> --checkpoint-path mobilenet_sgd_68.848.pth.tar --from-mobilenet

### ISSUE THREAD

**Issue by YOKE** [open-edge-platform/geti#99]
When I followed the guide :
![image](https://user-images.githubusercontent.com/34132063/60598081-ab139a80-9dde-11e9-9185-ce328edd7964.png)
In the second step, error occurred:
![image](https://user-images.githubusercontent.com/34132063/60598208-e01fed00-9dde-11e9-8938-98f1655e8d01.png)
And I noticed the place where the error occurred:
![image](https://user-images.githubusercontent.com/34132063/60599702-7b19c680-9de1-11e9-8d3c-027f904242cb.png)
However, there are not 'optimizer', 'scheduler' and ... in checkpoint
![image](https://user-images.githubusercontent.com/34132063/60599907-d6e44f80-9de1-11e9-8feb-864bd99a93f9.png)
##Environment
- Linux Ubuntu 16.04
- Python version:3.6.7
- Pytorch version:0.4.1
- CUDA/cuDNN version:
![image](https://user-images.githubusercontent.com/34132063/60598507-66d4ca00-9ddf-11e9-8f58-5784bf094675.png)
Can you help me?@Daniil-Osokin @AlexanderDokuchaev @grib0ed0v @snosov1   Very thankful!

**Comment by Daniil-Osokin** [comment]
I cannot reproduce this. BTW, `<LIP_HOME>` should be substituted to the real path to the dataset. This error may happen, if `--from-mobilenet` key is missed, make sure, that passed it.
